#!/bin/bash

PROJ_DIR="$(cd "`dirname $0`"/..; pwd)"
cd $PROJ_DIR

YES_REGEX='^([yY][eE][sS]|[yY])$'
RED_START='\e[31m'
GRN_START='\e[32m'
YLW_START='\e[33m'
COLOR_END='\e[0m'

git checkout develop 
echo "The following files have been modified:"
diff=`git diff master --name-only`
echo -e $YLW_START"$diff"$COLOR_END
read -r -p "!! PUSH TO REMOTE !! Are you sure you want to merge these changes into \`master\`? [y/n] " response
if [[ $response =~ $YES_REGEX ]]
then
    git checkout master && git merge develop
    git push
    git checkout develop
    echo -e $GRN_START"Successfully merged \`develop\` into \`master\`."$COLOR_END
else
    echo "Aborting merge for now"
    exit 0
fi
